services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
      - db
    networks:
      - node-network

  app:
    build:
      context: ./node
    container_name: app
    volumes:
      - ./node/:/usr/src/app/
      - /usr/src/app/node_modules
    # command: "npm install && npm start"
    tty: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/volume:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - node-network

networks:
  node-network:
    driver: bridge