services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - '8080:80'
    depends_on:
      - app
      - db
    networks:
      - node-network

  app:
    build:
      context: ./node
    container_name: app
    volumes:
      - ./node/:/usr/src/app
    tty: true
    depends_on:
      - db
    networks:
      - node-network

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - node-network

networks:
  node-network:
    driver: bridge